---
- name: Install nix
  ansible.builtin.shell: >-
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix |
    sh -s -- install --no-confirm
  args:
    creates: /nix/var/nix/profiles/default/bin/nix

- name: Copy profile.d files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /etc/profile.d/{{ item }}
  loop:
    - direnv.sh
    - Z50-devbox.sh

- name: Install docker
  ansible.builtin.shell: >-
    curl -fsSL https://get.docker.com -o install-docker.sh
    && sudo sh install-docker.sh
    && rm install-docker.sh
  args:
    creates: /usr/bin/docker

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    create_home: yes
    home: /home/{{ item.name }}
    groups:
      - docker
  loop: "{{ users }}"
