---
- name: Install nix
  ansible.builtin.shell: >-
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix |
    sh -s -- install --no-confirm
  args:
    creates: /nix/var/nix/profiles/default/bin/nix

- name: Copy profile.d files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /etc/profile.d/{{ item }}
  loop:
    - Z50-devbox.sh
    - direnv.sh
    - ssh-agent.sh

- name: Install docker
  ansible.builtin.shell: >-
    curl -fsSL https://get.docker.com -o install-docker.sh
    && sudo sh install-docker.sh
    && rm install-docker.sh
  args:
    creates: /usr/bin/docker

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    create_home: yes
    home: /home/{{ item.name }}
    groups:
      - docker
  loop: "{{ users }}"

- name: Provision asdf
  args:
    executable: /bin/bash
    creates: /usr/local/bin/asdf
  ansible.builtin.shell: >-
    curl -L https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-$(dpkg --print-architecture).tar.gz -o asdf.tar.gz \
    && mkdir -p ~/.config/fish/completions \
    && tar zxvf asdf.tar.gz \
    && mv asdf /usr/local/bin \
    && rm asdf.tar.gz
