---
<% if users|not-empty %>
users:
<% for i in users %>  - name: <{ i.name }>
    uid: <{ i.uid }>
<% endfor %>
<% else %>
users: []
<% endif %>

<% if remove-users|not-empty %>
remove_users:
<% for i in remove-users %>  - name: <{ i.name }>
    uid: <{ i.uid }>
<% endfor %>
<% else %>
remove_users: []
<% endif %>


ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHDKdUkY+SfRm6ttOz2EEZ2+i/zm+o1mpMOdMeGUr0t4 32617+amiorin@users.noreply.github.com
atuin_login: "{{ lookup('ansible.builtin.env', 'ATUIN_LOGIN') }}"
