---<% if repos %><% for x in repos %>
- name: Clone repo <{ x.org }>/<{ x.repo }>
  ansible.builtin.shell: >-
    git clone git@github.com:<{ x.org }>/<{ x.repo }> <{ x.repo }>/<{ x.branch }>
  args:
    chdir: code/personal
    creates: <{ x.repo }>/<{ x.branch }>
  tags: focus
  when: inventory_hostname == "<{ x.user }>"
<% for y in x.worktrees %>
- name: Create worktree <{ y }> for <{ x.org }>/<{ x.repo }>
  ansible.builtin.shell: >-
    git worktree add ../<{ y }> <{ y }>
  args:
    chdir: code/personal/<{ x.repo }>/<{ x.branch }>
    creates: ../<{ y }>
  tags: focus
  when: inventory_hostname == "<{ x.user }>"
<% endfor %><% endfor %><% endif %>
