# list of all recipes
help:
    @just -f {{ justfile() }} --list --unsorted

# backup dotfiles
backup:
    cp {{target}}/.config/fish/config.fish dotfiles/fish/config.fish
    cp {{target}}/.config/direnv/direnv.toml dotfiles/direnv/direnv.toml
    cp {{target}}/.config/zellij/config.kdl dotfiles/zellij/config.kdl
    cp {{target}}/.config/zellij/layouts/minimal.kdl dotfiles/zellij/layouts/minimal.kdl
    cp {{target}}/.doom.d/config.el dotfiles/doomemacs/config.el
    cp {{target}}/.doom.d/init.el dotfiles/doomemacs/init.el
    cp {{target}}/.doom.d/packages.el dotfiles/doomemacs/packages.el
    rsync -a --delete {{target}}/.doom.d/modules/lang/protobuf/ dotfiles/doomemacs/modules/lang/protobuf
    cp {{target}}/.config/atuin/config.toml dotfiles/atuin/config.toml
    cp {{target}}/.config/starship.toml dotfiles/starship/starship.toml

# install dotfiles
install:
    mkdir -p {{target}}/.doom.d/snippets
    rsync -a dotfiles/bin/ {{target}}/.local/bin
    cp dotfiles/starship/starship.toml {{target}}/.config/starship.toml
    rsync -a dotfiles/atuin/ {{target}}/.config/atuin
    cp dotfiles/git/gitconfig {{target}}/.gitconfig
    rsync -a dotfiles/fish/ {{target}}/.config/fish
    rsync -a dotfiles/direnv/ {{target}}/.config/direnv
    rsync -a dotfiles/zellij/ {{target}}/.config/zellij
    rsync -a dotfiles/doomemacs/ {{target}}/.doom.d
