name: Tests

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "/.gitignore"
    branches:
      - ansible

permissions:
  contents: write
  actions: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["21"]
        os: [ubuntu]

    runs-on: ${{ matrix.os }}-latest
    name: test-${{ matrix.os }}-temurin-${{ matrix.java-version }}

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - run: |
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: taiki-e/install-action@just

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: "Restore Cache"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

      - name: Setup Babashka
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: "latest"
          cli: "latest"

      - name: Tools Versions
        run: |
          java -version
          bb --version

      - name: Run tests
        run: |
          just test

  tag:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - id: set-artifact-tag-version
        run: echo "ARTIFACT_TAG_VERSION=0.2.$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - id: create-tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.set-artifact-tag-version.outputs.ARTIFACT_TAG_VERSION }}
          force_push_tag: true
